### ISSUE TITLE
View meteorite landings on a map

### ISSUE THREAD

**Issue by chef-louis** [chingu-voyages/v45-tier1-team-05#16]
**Feature Description**
A user needs to be able to view meteorite landings on an interactive map (drag & zoom in/out).

**1) User Stories**
- [x] Display an interactive global map with good performance / response times

**1) Tasks**
- [x] Select map service that meets criteria (free, able to support 45K+ points)
- [x] Import library
- [x] Set map options (zoom level, map boundaries)
- [x] Select and load base map
- [x] Draw points onto canvas
- [x] Stylize map and markers
- [x] Check responsiveness of map when dragging / scrolling

**2) User Stories**
- [x] Show/hide markers at landing site of selected/non-selected meteorites

**2) Tasks**
- [x] Clear existing canvas layer
- [x] Filter markers based on selection
- [x] Redraw markers onto canvas layer
- [x] Add to map

**3) User Stories**
- [x] Scale the marker by the size of the meteor

**3) Tasks**
- [x] Script CSS styling of marker radius based on "mass (g)" property
- [x] Check for errors

**4) User Stories**
- [x] Show/hide pop-up information of meteor when a marker is clicked/unclicked

**4) Tasks**
- [x] Bind pop-up info to markers
- [x] Stylize pop-up window

**5) User Stories**
- [x] Able to read elements on the map

**5) Tasks**
- [x] Add a legend

Additional Considerations
N/a
