### ISSUE TITLE
Count and Display Meteorites by Country

### ISSUE THREAD

**Issue by Stacy-Riley** [chingu-voyages/v45-tier1-team-05#18]
**Feature Description**
Convert lat/long into country
The data points will come into our app with latitude and longitude numbers. We need to convert these coordinates to find what country and/or continent the meteorite landed so that it can be marked on the map.

**User Stories**
The user will be able to to see what country the meteorite struck. There will be a drop down list of countries.

**Tasks**
- [ ] Dropdown list of country names showing on home screen
- [ ] Store Data in a variable to be used elsewhere in app
- [ ] Connect the leaflet.countrySelect plugin to the data points
- [ ] Handle Errors

**Feature Description**
_Create function to count the countries in the returned reverse geolocation data_
This feature gives the user the ability to see how many meteorites were recorded for a particular country.

**User Stories**
The user will be able to see how many meteorites have struck a particular country.

**Tasks**
- [ ] Decide where and how this feature will be displayed in the app. i.e. accessed from drop down menu or in a bar chart like in the sample?
- [ ] Count Data Points per Country with forEach
- [ ] Create Country-Count Mapping with Object.keys and .map to return country name and count
- [ ] HTML Dropdown Menu - if we are going this route
- [ ] Populate dropdown with data

**Comment by chef-louis** [comment]
Rolled into the broader Search Bar epic
