### ISSUE TITLE
Create function to count the countries in the returned reverse geolocation data

### ISSUE THREAD

**Issue by Stacy-Riley** [chingu-voyages/v45-tier1-team-05#19]
**Feature Description**
_Create function to count the countries in the returned reverse geolocation data_
This feature gives the user the ability to see how many meteorites were recorded for a particular country.

**User Stories**

- [ ] Decide where and how this feature will be displayed in the app. i.e. accessed from drop down menu or in a bar chart like in the sample?
- [ ] Count Data Points per Country with forEach
- [ ] Create Country-Count Mapping with Object.keys and .map to return country name and count
- [ ] HTML Dropdown Menu - if we are going this route
- [ ] Populate dropdown with data
