### ISSUE TITLE
Geolocation Button

### ISSUE THREAD

**Issue by jclegg31** [chingu-voyages/v45-tier1-team-05#21]
**__Feature Description__**
Button to display where user is currently located and the meteorite strikes around that location

**__User Stories__**
- [ ] User can click GeoLocation button and it will zoom to where they are located on the map 
- [ ] User can see within a determined radius what meteorites have struck around their location
- [ ] User can see on pop up or side bar a list of meteorite strikes based on their location for city, state, country, continent

**__Tasks__**
- [ ] Create button for UI
- [ ] Determine what mapping software will will be using and check geolocation functionality
- [ ] Check for default radius for initial location and display on map what is within that radius 
- [ ] Create modal box or sidebar with information based on location for city/state/country/continent 

**__Additional Considerations__**
What mapping we are using will determine the functionality. Google Maps has a lot of functionality 
https://developers.google.com/maps/documentation/javascript/geolocation

Leaflet, still looking into this as option.

**Comment by chef-louis** [comment]
Bug fix required: loss of map interactivity after geolocation button is enabled/disabled.

**Comment by chef-louis** [comment]
Fixed bug due to overlapping popup layers
