### ISSUE TITLE
Search bar features

### ISSUE THREAD

**Issue by chef-louis** [chingu-voyages/v45-tier1-team-05#25]
**__Feature Description__**
The search bar allows users to search for meteor strikes by location such as continent, country, or current geolocation or specifics such as name, size, year, etc.

**__User Stories__**
- [ ] Users want to search for meteor strikes by continent or country instead of the whole global map.
- [ ] Users want to view meteor strikes near their current location so they can see if any have struck nearby.
- [ ] Users want to search for specific meteors by name, size, or year to learn more about them.
- [ ] Users want to receive feedback if their search does not yield results.
- [ ] Users want to see indicators when the system is searching such as “in progress…”

**__Tasks__**
- [ ] HTML setup: input field, “Search” button, container
- [ ] User Input via JavaScript when button is clicked, also validate for an empty field or invalid characters
- [ ] Search Type Determination: Did the user type in-or select-a continent/country/etc.?
- [ ] Data Fetching: How will we store our data? API??
- [ ] Map Marker Display: the markers should change depending on search results
- [ ] Feedback i.e. No meteor strikes found
- [ ] Errors via API, geolocation, unexpected errors
- [ ] Testing various inputs: maybe we can simplify by using a drop-down menu in some cases such as country choice
- [ ] User Notes to describe what they can search for

**__Additional Considerations__**
- Ideally the use of the search bar will be intuitive with enough instruction for the user to use it successfully such as search suggestions
- We may want to display a loading graphic “…” if it takes a while to fetch data
- We should consider drop-down menus to prevent user typing errors if appropriate

**Comment by chef-louis** [comment]
Relevant items for country search bar have been added
