### ISSUE TITLE
Build structure of the wireframe into HTML

### ISSUE THREAD

**Issue by chef-louis** [chingu-voyages/v45-tier1-team-05#26]
**__Feature Description__**
Referencing the UI/UX wireframe [issue](https://github.com/chingu-voyages/v45-tier1-team-05/issues/22), the overarching structure of the application needs to be added to HTML.

**__User Stories__**
- [x] Create the overall layout of the wireframe within HTML

**__Tasks__**
- [x] Add a header (title)
- [x] Add a main div
- [x] Add a section for the search bar and geolocation button
- [x] Add a section for the map
- [x] Add a section for the summary statistics
- [x] Add a section for the data tables
- [x] Add a footer (incl. team details)

**__Additional Considerations__**

**Comment by chef-louis** [comment]
- [x] Add responsiveness for mobile
- [x] Collapse footer into column when sized down (flexbox)
