### ISSUE TITLE
Summary metrics component

### ISSUE THREAD

**Issue by chef-louis** [chingu-voyages/v45-tier1-team-05#39]
**Feature Description**
Meet minimum requirement to be able to see 'Summary Metrics' component on landing page

**1) User Stories**
- [x] User can see 'Summary Metrics' component on landing page

**1) Tasks**
- [x] Displays the following metrics for the data that has been selected:
- Total number of strikes
- Average mass
- Histogram showing number of strikes by year
- Histogram showing number of strikes by meteorite composition (recclass).
- [x] If no search criteria has been selected then the summary metrics will be for all meteorite strikes.
