### ISSUE TITLE
Detail Data Display Component

### ISSUE THREAD

**Issue by chef-louis** [chingu-voyages/v45-tier1-team-05#40]
**Feature Description**
Meet minimum requirement to be able to see a scrollable detail data display containing the meteorite strike history based on the search criteria

**1) User Stories**
- [x] User can see 'Detail Data Display' component on landing page

**1) Tasks**
- [x] Display is scrollable
- [x] Displays one row for each meteorite strike in the data set.
- [x] If no search criteria has been selected then the summary metrics will be for all meteorite strikes.
